filetype on "Colour of the text... I think...
syntax on "Colour of the text... I think

set number "Display number of rows...
set colorcolumn=80 "Print a colour column to know when to change line when possible...
set hlsearch "Highlight pattern in search...
set incsearch "Enhanced search... Dinamically search as I write...
set showmatch "View matching parenthesis... Actually moves the cursor for a second to the beguining of the pair...
set wrap linebreak nolist "Soft wrap (without inserting new line).

set expandtab     "┐
set shiftwidth=4  "├These allow vim to use spaces instead of tabs... 
set softtabstop=4 "┘
set autoindent


